# keytool -genkeypair -alias mytestkey -keyalg RSA -keypass changeme -keystore keystore.jks -storepass letmein

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop


server:
  port: 9000
